### ISSUE TITLE
403 Forbidden response

### ISSUE THREAD

**Issue by mosesab** [green-api/whatsapp-chatbot-python#2]
I keep getting a 403 Forbidden response.

![Screenshot_20230530190025](https://github.com/green-api/whatsapp-chatbot-python/assets/87482913/e944f5fa-35e3-4360-9dae-be23961d086d)

![Screenshot_20230530190124](https://github.com/green-api/whatsapp-chatbot-python/assets/87482913/e5cf7040-3f25-481b-8a9c-bb1376711d75)

**Comment by EscHelpNew** [comment]
Hello, please write to support on the site, indicate your instance number, they will help you.

**Comment by EscHelpNew** [comment]
Most likely this error occurs due to an incorrect request to the API.
Recommended:
1. Use a special postman collection for API testing (this collection has already been checked and tested), and only after that, transfer the checked requests to the code.
Description - https://green-api.com/en/docs/postman-collection/
Collection - https://github.com/green-api/green-api-postman-collection
2. Use ready libraries https://green-api.com/en/docs/sdk/

**Comment by mosesab** [comment]
It seems I was making a mistake while formatting the url. It's fixed now. I decided to use the library. Thank you.

![Screenshot_20230531130356](https://github.com/green-api/whatsapp-chatbot-python/assets/87482913/32d3ca96-c99a-41e8-bf27-b9d1541e2631)

![Screenshot_20230531130310](https://github.com/green-api/whatsapp-chatbot-python/assets/87482913/7ee2e4f0-a7e2-4ac4-929c-38735bcbd40e)
