### ISSUE TITLE
how to reply message in group?

### ISSUE THREAD

**Issue by tahik32987249732094** [green-api/whatsapp-chatbot-python#37]
![image](https://github.com/green-api/whatsapp-chatbot-python/assets/69989225/84a94b2e-d231-4a77-8b4e-8b4bcfef815c)
this is just a message how to reply that message

**Comment by lent0s** [comment]
**Good afternoon!**
In order to reply to a message, you need to use a method, for example, **[SendMessage](https://green-api.com/en/docs/api/sending/SendMessage/)**, where in the `quotedMessageId` field add the `idMessage` of the required message

You can find out the `idMessage` using the following methods:
- **[GetChatHistory](https://green-api.com/en/docs/api/journals/GetChatHistory/)**
- **[LastIncomingMessages](https://green-api.com/en/docs/api/journals/LastIncomingMessages/)**

Also, for your convenience and promptness of our responses, please contact our technical support at **[Green-API](https://green-api.com/en)** site

Write to **Issues** on GitHub what **errors** and **bugs** you encountered so that we transfer the tasks to the developers

**Comment by tahik32987249732094** [comment]
ohh thanks
